baseURL = "https://johnnyhurts.com/"
languageCode = "en-us"
title = "johnny hurts"
theme = "archie"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "G-YKXESPLGL9"

[params]
    author = "Johnny Chang"
    # description = "Personal blog theme powered by Hugo"
    githubUsername = "hiimdoublej"
    accent = "grey"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    # highlightStyle = "default"
    # highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/hiimdoublej/"

[[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://www.linkedin.com/in/hiimdoublej/"
